language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bobbyvann/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bobbyvann/react-test npm test

after_success:
  - docker build -t bobbyvann/multi-client ./client
  - docker build -t bobbyvann/multi-nginx ./nginx
  - docker build -t bobbyvann/multi-worker ./worker
  - docker build -t bobbyvann/multi-server ./server

  #Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take those images and push them to docker hub
  - docker push bobbyvann/multi-client
  - docker push bobbyvann/multi-nginx
  - docker push bobbyvann/multi-worker
  - docker push bobbyvann/multi-server

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-568123056836'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
